make: NightKing.java q4src/
	javac NightKing.java

run: make
	java NightKing

ll: make
	java q4src.MyLinkedList

llq: make
	java q4src.LLQueue

clean:
	rm -f *.class *~ *\#
	rm -f */*.class */*~ */*\#
