make: in2.txt TeamSelection.java q2src/DLL.java q2src/MyIterable.java q2src/MyIterator.java
	javac TeamSelection.java

run: make
	java TeamSelection

debug: make
	java q2src.DLL

clean:
	rm -f *.class *~ *\#
	rm -f */*.class */*~ */*\#
