make: in2.txt TeamSelection.java questionTwo/DLL.java questionTwo/MyIterable.java questionTwo/MyIterator.java
	javac TeamSelection.java

#	javac 

run: make
	java TeamSelection

test: make
	java mySrc.DLL

clean:
	rm -f *.class *~ *\#
	rm -f */*.class */*~ */*\#
